### ISSUE TITLE
Cannot read property 'measure' of undefined

### ISSUE THREAD

**Issue by jeroenbourgois** [gitim/react-native-sortable-list#1]
Hi 

I tried to copy the example as good as possible but I keep getting `Cannot read property 'measure' of undefined`. I saw in the source that there is a `_container` where the `measure` is called upon, but I don't really get or see how the `_container` is set?

**Comment by gitim** [comment]
Hi! It is set in https://github.com/gitim/react-native-sortable-list/blob/master/src/SortableList.js#L434. It is strange, that you get error, because I rechecked the example and it works fine.

**Comment by jeroenbourgois** [comment]
Maybe it is my RN version. What version are you on?

**Comment by jeroenbourgois** [comment]
I think we can ditch this... Opened the same repo on another computer and everything went just fine...

**Comment by gitim** [comment]
> What version are you on?

0.35

> I think we can ditch this... Opened the same repo on another computer and everything went just fine...

cool!
