### ISSUE TITLE
when i sort the list that's crash on Android.

### ISSUE THREAD

**Issue by maxing19920124** [gitim/react-native-sortable-list#10]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by hungdev** [comment]
i have same error. it discuss here https://github.com/gitim/react-native-sortable-list/issues/2

**Comment by joshuapinter** [comment]
Duplicate of #2. Suggest closing.

**Comment by joshuapinter** [comment]
See my issue and resulting PRs over at #15.

**Comment by gitim** [comment]
works in master, will release a version very soon
