### ISSUE TITLE
Example broken on Android with RN 0.41

### ISSUE THREAD

**Issue by chetstone** [gitim/react-native-sortable-list#11]
The upgrade in commit 29019cc754b9a56a8e8f0df4eeb9e6a297c2f7ab breaks the android example because of a [breaking change](https://github.com/facebook/react-native/releases/tag/v0.41.0) in react-native. The fix is a simple change in MainApplication.java.

But after doing that I run into Issue #2. I guess that's still not fixed, in spite of commits with comments "Android Fix" ?

**Comment by gitim** [comment]
it does not work because example install the module from npm, but I have not yet published a new version with fixes

**Comment by chetstone** [comment]
Ah yes, of course. Sorry to bother you.
