### ISSUE TITLE
Reorder not working in android when inside scroll view

### ISSUE THREAD

**Issue by preetipantnagar1989** [gitim/react-native-sortable-list#118]
<HeaderImageScrollView
        maxHeight={DETAILED_NAV_MAX_HEIGHT}
        minHeight={DETAILED_NAV_MIN_HEIGHT}
        headerImage={ImgSource}
        renderFixedForeground={() => this.renderHeader()}
        scrollEnabled={this.state.scrollEnable}
        bounces={false}
      >
          <View
            style={{
              height: includedLinkListHeight
            }}
          >
            <ReorderList
              data={this.props.includedLinks}
              title={this.includedListTitle}
              titleStyle={styles.sectionTitle}
              renderRow={(rowData: any) => this.renderRow(rowData)}
              titleBackgroundStyle={styles.titleBackgroundView}
              contentContainer={[styles.contentContainer]}
              onReleaseRow={(rowKey: string) => this.onReleaseRow(rowKey)}
              onChangeOrder={(nextOrder: any) => this.onChangeOrder(nextOrder)}
              onActivateRow={(rowKey: string) => this.onActivateRow(rowKey)}
            />
          </View>
</HeaderImageScrollView>

**Comment by preetipantnagar1989** [comment]
Started working .. just need to comment below responder from the Row.tsx.
 onShouldBlockNativeResponder: () => {
      // Returns whether this component should block native components from becoming the JS
      // responder. Returns true by default. Is currently only supported on android.
      // NOTE: Returning false here allows us to scroll unless it's a long press on a row.
      return false;
    },

**Comment by shubhanus** [comment]
Where we have to place it ?

**Comment by aniltirola** [comment]
Thanks for the advice. The solution for me consists of 2 steps

1#

```
// file Row.tsx.
onShouldBlockNativeResponder: () => {
  return true;
},
```

2#
Be aware that `ReorderList` list ist embedded in another `View` which has a padding. This guarantees that the user can decide if
- he touches outside the `ReorderList` in the padding-area, then the user can move the scrollview
- or he touches inside the `ReorderList`, then scrollview is locked, and `ReorderList` acts as expected

**Comment by saransh-malik** [comment]
I am still facing this issue, could you like help me on how did you guys fixed it?
