### ISSUE TITLE
Scrolling doesn't work on Android

### ISSUE THREAD

**Issue by chetstone** [gitim/react-native-sortable-list#12]
Using b931565ca30137e85087880a28028d1c1635beed, it looks like Issue #2 is now fixed, thanks!!

But when you short press and drag an item in the example, it picks it up and and moves it, rather than scrolling the list. Works as expected on iOS.

Thanks.

**Comment by gitim** [comment]
yes, there is problem with scrolling on android and it is a blocker for the release, can not fix it yet.

**Comment by joshuapinter** [comment]
See my issue and resulting PRs over at #15.

**Comment by gitim** [comment]
confirm, now seems it works fine
