### ISSUE TITLE
undefined is not a function (near 'renderRow')

### ISSUE THREAD

**Issue by gabriellaquattrone** [gitim/react-native-sortable-list#123]
The error is when I try to use the basic example. I think it happens with the data variable.
`<SortableList
                  style={styles.list}
                  contentContainerStyle={styles.contentContainer}
                  data={data}
                  renderRow={this._renderRow} />`

**Comment by AnurajDev** [comment]
@gabriellaquattrone Did you solve this error? If yes, how exactly?
