### ISSUE TITLE
Issues with react native 0.57

### ISSUE THREAD

**Issue by scaralfred** [gitim/react-native-sortable-list#131]
After upgrading react native from 0.55.4 to 0.57.1 an issue came out. With a minimum of interactions, rows start changing order themselves, tending to focus on the first position... and I'm not moving them manually.
I'm sure this issue is related to the compatibility with react native 57, as react native 55.4 runs perfectly.
What is happening is that if I interact with a single row, the entire group of rows re-renders, moving that row to the first position. 
I think the interested lines of code are those with the variables NextData and NextOrder

**Comment by damikdk** [comment]
If you can, try `autoscrollAreaSize={-100}`

**Comment by scaralfred** [comment]
@damikdk Thanks man, but is not working. Rows keep beeing crazy :(

**Comment by scaralfred** [comment]
They just released react native 0.57.5 but it didn't fix the issue
