### ISSUE TITLE
Rows with TextInput

### ISSUE THREAD

**Issue by ajostergaard** [gitim/react-native-sortable-list#14]
Hi - I would like my rows to have a TextInput so that, for example, somebody can rename the cats inline. Unfortunately the TextInput loses focus after each key press, looks like the redraw creates a new list. I assume TextInput simply can't be supported but thought I'd ask?

**Comment by gitim** [comment]
Hi! I tried to modify the example and make rows' titles editable, and it works:
![-12-2017 08-02-28](https://cloud.githubusercontent.com/assets/3778452/22859796/28abdafa-f0fa-11e6-8b67-b1271e21ed01.gif)
Maybe I something missing could you provide gist with your code.

**Comment by ajostergaard** [comment]
That's actually really good news for me, thanks!!! My code is a bit all over the place still and I'm very new to React & React Native - any chance you could share yours?

**Comment by gitim** [comment]
Here https://github.com/gitim/react-native-sortable-list/blob/textinput/examples/Basic/index.js I pushed it to separate branch.

**Comment by ajostergaard** [comment]
You're absolutely right and thank you for your patience! I was pushing each key change up to the parent state and the list was being recreated as a result... Keeping the row text state local like you did is obviously much smarter. :)

**Comment by Abhijeetjaiswalit** [comment]
do we have an example/code of editable title thing? i'm facing trouble doing that. @ajostergaard @gitim

**Comment by ajostergaard** [comment]
@Abhijeetjaiswalit sorry - I haven't done any mobile dev at all for a few years now so cannot help.
