### ISSUE TITLE
Warnings in RN 0.61

### ISSUE THREAD

**Issue by mifi** [gitim/react-native-sortable-list#167]
componentWillReceiveProps and componentWillMount are being used by this package, but they are now deprecated by react and their use discouraged. This causes warnings in newest react native. Needs to be rewritten. See:
https://reactjs.org/docs/react-component.html#unsafe_componentwillmount
https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by DenisSokoloff** [comment]
![image](https://user-images.githubusercontent.com/18741464/71240751-98e8d280-2312-11ea-9275-271059b85c77.png)

**Comment by surya-moven** [comment]
This should take care of them: https://github.com/gitim/react-native-sortable-list/pull/192
