### ISSUE TITLE
Basic Example is giving error of Failed prop type: Invalid prop decelerationRate of value normal supplied to App.js, expected one of [null,null]

### ISSUE THREAD

**Issue by anil3a** [gitim/react-native-sortable-list#193]
Hi guys, I am new here and I tried to copy App.js from Basic example and put in my SortableMyList.js file to see how it works. There is big error in my console and i have no idiea what is it. I tried to Google it and search these type of error but couldn't find any. 
Sorry I don't know where to ask, let me know if i need to ask this somewhere else.

Here is the screenshot of my code, browser running expo react native and error in console.

![image](https://user-images.githubusercontent.com/2561627/79923540-11a29b80-8479-11ea-8c85-40743c5fa4e8.png)

Here is my package.json dependencies
```
"dependencies": {
    "@expo/vector-icons": "~10.0.6",
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.3",
    "expo-constants": "~9.0.0",
    "expo-font": "~8.1.0",
    "expo-web-browser": "~8.1.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-sortable-list": "0.0.24",
    "react-native-swipe-list-view": "^2.5.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~37.0.0"
  },
```

Thank you

**Comment by PeturSigurdsson** [comment]
You could change Line 35 of sortableList.js  to ... oneOfType(... instead of ... oneOf(...  .
oneOf needs a value while oneOfType can take a general type like string or number. If oneOf gets a type without a value, like it does here, the value will be null.

**Comment by anil3a** [comment]
Thanks for the suggestion, it worked. I hope the issue get fixed in the original code. Do you think this issue should be closed ? Also question, if i build my project with this manual fix, will it be a problem ?

**Comment by PeturSigurdsson** [comment]
If you fix it manually you should keep it outside of node_modules in a lib folder or something. Otherwise it could be a source of annoyance, since package managers will update it periodically and undo your manual fix.

**Comment by bureyburey** [comment]
@anil3a another solution would be using <a href="https://www.npmjs.com/package/patch-package">patch-package</a> to create a patch that is applied to the node_modules.

It would be advisable to lock the react-native-sortable-list version in the package.json file as long as you are using the patch
