### ISSUE TITLE
Row.js formatting confusion

### ISSUE THREAD

**Issue by wildQueequeg** [gitim/react-native-sortable-list#23]
Can someone explain why the rows have this spacing when {position: 'absolute'} on Row.js is removed? The content height is the same as if there isn't extra space, but the Rows are very far apart from each other.

<img width="305" alt="screen shot 2017-03-13 at 10 01 20 am" src="https://cloud.githubusercontent.com/assets/8702001/23857665/600989e8-07d4-11e7-9a6e-7a411e1ceb6a.png">

**Comment by gitim** [comment]
Because for rows positioning top is used, and if positioning of element is not absolute this rule is used

> When position is set to relative, the top property specifies the distance the element's top edge is moved below its normal position.

https://developer.mozilla.org/en-US/docs/Web/CSS/top
