### ISSUE TITLE
Invariant Violation: ViewPropTypes has been removed from React Native.

### ISSUE THREAD

**Issue by Shade14** [gitim/react-native-sortable-list#246]
I was trying to use the package in an expo project and I get this issue that: 
ViewPropTypes has been removed from React Native, and to migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:40 in guardedLoadModule
at http://192.168.1.9:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in global code

I don't know if this issue is expo related or it's a common issue. If you can elaborate or fix that would be awesome and thank you.

**Comment by tanzeel152** [comment]
In your project package.json file replace  "react-native-sortable-list": "https://github.com/gitim/react-native-sortable-list#78c8ec0e66ba792784131065fbeab3f365deb0dc" with your version
