### ISSUE TITLE
onPress Row?

### ISSUE THREAD

**Issue by wildQueequeg** [gitim/react-native-sortable-list#25]
Is it possible to add an onPress function to the entire row without upsetting the sorting?

**Comment by gitim** [comment]
Do you want something like onPressRow `(key) => void` to subscribe on presses, I think it is easy to add.

**Comment by wildQueequeg** [comment]
Yes exactly that

**Comment by gitim** [comment]
added, released 0.0.7

**Comment by wildQueequeg** [comment]
Thank you!
