### ISSUE TITLE
Active record is much lower than the finger on the screen

### ISSUE THREAD

**Issue by Stormsher** [gitim/react-native-sortable-list#27]
Active record is much lower than the finger on the screen. How to solve this?

**Comment by gitim** [comment]
I don't understand your problem, could you provide more details, also it will be good to attach some screenshots.

**Comment by gitim** [comment]
Is this still actual?

**Comment by Stormsher** [comment]
Yes..

**Comment by i8wu** [comment]
@Stormsher Do you want to provide more info?

**Comment by gitim** [comment]
Can't help without additional information, close this.
