### ISSUE TITLE
Question: does the sortable feature also work with a horizontal list?

### ISSUE THREAD

**Issue by ranjitpandit** [gitim/react-native-sortable-list#29]

**Comment by gitim** [comment]
nope, horizontal orientation is not supported

**Comment by ranjitpandit** [comment]
Thanks. Any tips on how it could be supported? I can try and work on it.

**Comment by i8wu** [comment]
@ranjitpandit I'm also interested in that functionality. Took a look at the source and it seems doable. You'll need to add a horizontal prop and find all the areas in the code that will need an if/else. Some notable places I see are 
-_renderRows() dynamically sets the y coord for each row item
-_onMoveRow probably does something to ensure there's no dragging left/right

I might take a look at implementing horizontal-ness if I have time, but if you wanna do it, I'm all for it.

**Comment by gitim** [comment]
Implemented this feature in the branch https://github.com/gitim/react-native-sortable-list/tree/horizontal, will release it soon.

**Comment by gitim** [comment]
released https://github.com/gitim/react-native-sortable-list/releases/tag/v0.0.9

**Comment by ranjitpandit** [comment]
The example Horizontal app looks great! Thank you for adding this feature.
