### ISSUE TITLE
Adding new data to list ala Redux

### ISSUE THREAD

**Issue by 1800joe** [gitim/react-native-sortable-list#3]
First off, nice work with the library! There seems to be a bug when adding new data to the sortable list. It looks like when the component receives new props the data and subsequently the layout items are not updated, but the order is. 
So when the list attempts to re-render it uses the order array to key into the data blob, but the item is not there (just a theory at the moment).

**Comment by aaggarwa88** [comment]
Iam also waiting for this to be released.. please let me know when this feature gets merged to master

**Comment by gitim** [comment]
Implemented this feature in 0.0.5, please, give some feedback.
