### ISSUE TITLE
Touchable* inside Row element

### ISSUE THREAD

**Issue by tbenshalom** [gitim/react-native-sortable-list#31]
Hi,
When I have Touchable* element inside "row", the touchable element not receiving the touch event, and its "onPress" event do not raise.
I think reason is in this line in Row.js:
onMoveShouldSetPanResponder: () => !this._isDisabled(),

if I'm replacing it with the following line, all works:
onMoveShouldSetPanResponder: () => false,

But I'm new to RN and I'm not sure if its the correct way to "fix" this issue, and what can be the implications.

There is better way to solve this issue?

Thanks,
Tal

**Comment by i8wu** [comment]
Tested your solution and it seems to break the draggability of the row item, so this actually isn't a solution. I'll try to take a look since I'm interested too.

**Comment by i8wu** [comment]
```
  _isDisabled() {
      return this.props.disabled ||
        this._isAnimationRunning && this.props.disabledDuringAnimation;
    }
```
Looks like `this.props.disabledDuringAnimation` is actually undefined, deleting this allows touchable to receive the touch and doesn't break dragging. @gitim I can submit a PR if you'd like.

**Comment by gitim** [comment]
yes, please

**Comment by gitim** [comment]
published, a new version with fix
