### ISSUE TITLE
Ability to drag out of the list (x-axis movement) 

### ISSUE THREAD

**Issue by klvs** [gitim/react-native-sortable-list#32]
Hi, first off, great work! 

I'm looking to use this component to sort a list but also remove items by dragging them out of the list. The deletion doesn't seem tricky because you can pass it a new data set, but currently you can only move items along the y-axis, not x. Thus there would be no way to move it off to the side signifying deletion.

Is there an option for this I'm not seeing? If not, any pointers toward what would need to change? Or is it all together built around only working along the y axis and might be struggle?

Thanks!

**Comment by i8wu** [comment]
Don't think the module currently supports that kind of action, although it sounds a bit iffy to me. Do you have a screenshot/mockup of what you expect it to act like?

**Comment by gitim** [comment]
Hi, currently there is no such option. I recently saw an article in medium about animations and particularly about swipeable card animation: https://hackernoon.com/moving-beyond-animations-to-user-interactions-at-60-fps-in-react-native-b6b1fa0ba525, also you can look at [SwipeableRow](https://github.com/facebook/react-native/blob/v0.44.0-rc.0/Libraries/Experimental/SwipeableRow/SwipeableRow.js) from react native, maybe it will be useful for you.

**Comment by klvs** [comment]
Thanks for the link! That was a really good read and led me to [wix's react-native-action-view](https://github.com/wix/react-native-action-view). It could be integrated into this repo (though I've yet to try) but maybe it's best left open ended? I wouldn't mind throw in a PR when I find the time if folks are interested.

**Comment by gitim** [comment]
Since 0.0.19  SwipeRow  from the react-native-swipe-list-view can be used with react-native-sortable-list, so I think the issue can be closed.
