### ISSUE TITLE
onChangeOrder callback

### ISSUE THREAD

**Issue by i8wu** [gitim/react-native-sortable-list#36]
Seems like onChangeOrder calls back everytime a row passes by another row. Not sure if this entirely makes sense to happen. I think it should only callback after moving has stopped. Or is there another property/config for me to see onChangeOrder after onRelease?

**Comment by i8wu** [comment]
Doing this works I guess, not sure if it's that great though:
```
onChangeOrder={(nextOrder) => { this._order = nextOrder; }}
onReleaseRow={(key) => myFunc(this._order)}
```

**Comment by gitim** [comment]
It is desirable behaviour. Your solution is valid.
