### ISSUE TITLE
refreshControl for SortableList

### ISSUE THREAD

**Issue by sam-n-johnston** [gitim/react-native-sortable-list#38]
First of all, this is a great module! Works nicely, the animation are smooth and the usage is super easy! 

I need a refreshControl on the SortableList. I can submit a PR on the weekend for this if it's ok with you. I was thinking of adding a prop `refreshControl` and passing it down to the SortableList's ScrollView. Would this be OK?

**Comment by gitim** [comment]
> First of all, this is a great module! Works nicely, the animation are smooth and the usage is super easy!

thanks!

> Would this be OK?

yes, it will be ok

**Comment by sam-n-johnston** [comment]
It's going to be more complicated than I previously estimated. On android, the pull-down refresh is activated event when we long press a row. I'll have to look more into it when I have time.

**Comment by gitim** [comment]
released in 0.0.11
