### ISSUE TITLE
Switch inside of Row

### ISSUE THREAD

**Issue by i8wu** [gitim/react-native-sortable-list#40]
Seeing weird behavior with having a Switch component inside the row. Sometimes pressing a switch will count as a long press and breaks a row. It doesn't seem to be too consistent, in that it doesn't happen every time the switch is pressed. 

https://gfycat.com/BonyHollowAnnashummingbird

**Comment by i8wu** [comment]
I have a semi-working hack, but it isn't ideal at all.
```
Row.js
onPanResponderGrant: (e, gestureState) => {
if (gestureState.x0 > 300) {
    return;
}
```
Basically makes right side of the row not grabbable

**Comment by gitim** [comment]
Try to increase [ACTIVATION_DELAY](https://github.com/gitim/react-native-sortable-list/blob/master/src/Row.js#L5) of the Row, if this will fix the issue, we can expose that property to the api.

**Comment by i8wu** [comment]
Thanks for the suggestion, but doesn't seem to help. The activation doesn't seem to just be from the initial press on the switch, the switch just sometimes holds onto the press as a press down. Is there any way to detect that a touch event is bubbled from a switch?

**Comment by gitim** [comment]
There is event.native.target, but it is just id, and it is useless in this case. I wonder why fires onPanResponderGrant  without onPanResponderRelease on Row after pressing Switch.

**Comment by i8wu** [comment]
Hmm...do you know of a way to check if a component is a switch? Maybe if we could do that we could designate untouchable areas for the rows?

**Comment by gitim** [comment]
> Hmm...do you know of a way to check if a component is a switch?

No. But even if we can it will be just workaround and not good solution.

**Comment by i8wu** [comment]
Hm, what does
```onPanResponderGrant: (e, gestureState) => {
      e.persist();```
do?

**Comment by i8wu** [comment]
I think changing this to true fixes my issue? Will need to test more
https://github.com/facebook/react-native/blob/a6df7a6ce7111e9f281007d80b3809d775928439/Libraries/Components/Switch/Switch.js#L101

**Comment by gitim** [comment]
> Hm, what does
>
> onPanResponderGrant: (e, gestureState) => {
>      e.persist();
> do?

by default react native reuse event objects for performance reason, if you need to indicate to react native that this event should be saved and will be used later, you need to call persist (see https://github.com/facebook/react-native/blob/703936d9e30d6d7c25013281459d2fcf86244a77/Libraries/Renderer/src/renderers/shared/shared/event/SyntheticEvent.js#L54)

**Comment by i8wu** [comment]
For anyone that comes across this issue...I ended up wrapping my switch in a Pansponder that does not allow TerminationRequests.
