### ISSUE TITLE
The list still scrolls even with scrollEnabled=false

### ISSUE THREAD

**Issue by jbrodriguez** [gitim/react-native-sortable-list#41]
Initially, the list won't scroll (expected).

But after your drag/drop a row, scrolling is now enabled (despite scrollEnabled=false).

I traced it to [this line](https://github.com/gitim/react-native-sortable-list/blob/master/src/SortableList.js#L520). Disabling it, makes it work as expected.

Any thoughts ?

**Comment by i8wu** [comment]
Looks like that line should probably be `scrollEnabled: this.props.scrollEnabled` ? @gitim

**Comment by gitim** [comment]
yes, you are right. It was bug, fixed in 0.0.10
