### ISSUE TITLE
Disable the opacity animation on mounting and updating.

### ISSUE THREAD

**Issue by monlu** [gitim/react-native-sortable-list#42]
Hello! I'm really enjoying this library so far. Great job!

Everything works great, except I don't see an option that allows me to disable the animated opacity when the component is mounted/updated.

Maybe I am missing something? If not it doesn't seem very difficult to implement anyway. I also wouldn't mind submitting a PR!

Thanks again!

**Comment by gitim** [comment]
Hi! Currently there is no option to disable this animations. I added this animations initially, but know I doubt that this decision was correct, seems it is possible and it would be better to implement them in userland. I think we can just drop them.
