### ISSUE TITLE
Render footer at end of list?

### ISSUE THREAD

**Issue by jlo1** [gitim/react-native-sortable-list#46]
Is it possible to render a footer at the end of the list (or any plans to support in the future)? Trying to add an "add" button at the end of the list, but don't want the footer view to be sortable.

**Comment by gitim** [comment]
Currently no, but I have private version of this component with `renderFooter` api, I didn't introduced this api to open source, because thought it is useless for common use cases, but I can add it.

**Comment by jlo1** [comment]
Yes please! That would be amazing to add that functionality.

**Comment by gitim** [comment]
pushed to the master, you can try it by installing the module from git. But there is an issue:
![simulator screen shot 13 2017 0 15 59](https://cloud.githubusercontent.com/assets/3778452/26017276/7036b4cc-3771-11e7-8dcd-8ca67a3a28d1.png)
while dragging a row, it remains under the footer, I solved this in private repo, just need to remember how I did it :) Will release a new version after fix this.

**Comment by gitim** [comment]
fixed, released in 0.0.12

**Comment by diego-caceres** [comment]
Hi there. I think theres a bug now when you don't have a footer: "null is not an object (evaluating 'footerLayout.height')" 
May it be because of this feature?

**Comment by gitim** [comment]
Hi @diego-caceres, thanks, missed this, fixed in 0.0.13
