### ISSUE TITLE
list items don't stretch horizontally

### ISSUE THREAD

**Issue by mocanSergiu666** [gitim/react-native-sortable-list#49]
I cannot find a way to stretch the items of the list. Why don't they stretch implicitly?

**Comment by i8wu** [comment]
Have you set flex or flexGrow? It shouldn't be up to the module to decide how your rows are styled.

**Comment by gitim** [comment]
Could you provide some screenshots or example, what do you expect and what you receiv?

**Comment by mocanSergiu666** [comment]
This one was my problem. [https://stackoverflow.com/questions/44240400/react-native-sortable-list](https://stackoverflow.com/questions/44240400/react-native-sortable-list)
But now I use react-native-sortable-listview and it works fine.

**Comment by escobar5** [comment]
Having the same problem, I have alignSelf: 'stretch' to rows

**Comment by kylanhurt** [comment]
+1 there appears to be an issue that does not allow the use of flex or a % for width of the render component. I am going to have to set it explicitly. This definitely needs to be fixed!

**Comment by cstd** [comment]
+1
