### ISSUE TITLE
Component doesn't render second time in same parent view

### ISSUE THREAD

**Issue by luisfuertes** [gitim/react-native-sortable-list#50]
I need set list order on componentDidMount().

Im trying to set like `order={["0", "4", "3", "1", "2"]}` on SortabeList props. But it does not seem to work. I use same structure that i receive on onChangeOrder method.

And another problem I have is that componentDidMount() is called after component render.

If i set "order" prop after SortableList is rendered (I set it on componentDidMount) it should work?

Can you add a litle documentation of structure of order prop array?

And maybe some method to force the list order?

Thanks!

**Comment by i8wu** [comment]
Why not reorder your object? Also if you want something to happen before render you should put it in componentWillMount.

**Comment by luisfuertes** [comment]
How is the array format? I try with `order={["0", "4", "3", "1", "2"]}` and it doesnt works

**Comment by i8wu** [comment]
Are the keys for your object ["0", "4", "3", "1", "2"] ?

**Comment by gitim** [comment]
just test, everything is working, [here](https://github.com/gitim/react-native-sortable-list/commit/40dbf3e7df865241b29edd1d30f412857ab5870c) modified example

**Comment by luisfuertes** [comment]
Ok i only forgot update order state on onChangeOrder method.

Now order works, but dont know why, component dont render elements. I think is because the sortable-list dont render always. Render it dynamically when i need it.

Debugging i have seen that this `setState` is never called to set the opacity to 1.
``` 
  _onUpdateLayouts() {
    Promise.all([this._footerLayout, ...this._rowsLayouts])
      .then(([footerLayout, ...rowsLayouts]) => {
        // Can get correct container’s layout only after rows’s layouts.
        this._container.measure((x, y, width, height, pageX, pageY) => {
          const rowsLayoutsByKey = {};
          let contentHeight = 0;
          let contentWidth = 0;

          rowsLayouts.forEach(({rowKey, layout}) => {
            rowsLayoutsByKey[rowKey] = layout;
            contentHeight += layout.height;
            contentWidth += layout.width;
          });

          this.setState({
            containerLayout: {x, y, width, height, pageX, pageY},
            rowsLayouts: rowsLayoutsByKey,
            footerLayout,
            contentHeight,
            contentWidth,
          }, () => {
            this.setState({animated: true});
          });
        });
      });
  }
``` 
This:
``` 
          () => {
            this.setState({animated: true});
          });
``` 

If i hardcode it to `opacity: 1`, content not rendered either.

My package versions: 
```
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.3",
		"react-native-sortable-list": "0.014",
```

**Comment by gitim** [comment]
you are using react@16, maybe setState behaviour/api changed

**Comment by luisfuertes** [comment]
Tomorrow i will try to downgrade react version to 15.5.4.

**Comment by luisfuertes** [comment]
I found these issues
https://github.com/airbnb/enzyme/issues/953

I downgrade my project versions to your example react versions and bug keep going. Dont know if for setState callback. Im going to debugging now.
``` 
		"react": "15.4.0",
		"react-native": "0.41.2",
```

**Comment by luisfuertes** [comment]
Ok after first render, in second render setState callback isnt called.

With react versions:
``` 
"react": "15.4.0",
"react-native": "0.41.2",
```

**Comment by luisfuertes** [comment]
@gitim any idea of how can i fix it?
