### ISSUE TITLE
Elements of different heights

### ISSUE THREAD

**Issue by escobar5** [gitim/react-native-sortable-list#52]
I have a list with items of different heights, but if I don't define height for the row, then there is a spacing between items, are different height elements not supported?

**Comment by gitim** [comment]
Initially different height elements are supported, but after adding horizontal direction support it was broken, I think I can fix this.

**Comment by escobar5** [comment]
I think the problem was mine, it is working fine. Thanks

**Comment by davidcorbin** [comment]
@gitim Was this ever fixed? Still having issues adding elements of different heights.

**Comment by daybreaker** [comment]
Same here. Love when people fix something but then dont tell us how :-/
