### ISSUE TITLE
Callback functions passed to row item do not work.

### ISSUE THREAD

**Issue by DigohD** [gitim/react-native-sortable-list#55]
When passing functions as props to row items they do not work. The TouchableOpacity elements I use to call them flash on press, however, so they clearly recognize the press event. I've only tested this on my Samsung Galaxy Note 3. I also attach the whole file.
[BackPoints.txt](https://github.com/gitim/react-native-sortable-list/files/1082543/BackPoints.txt)

Here is the SortableList element:

    <SortableList	style={layoutStyles.listWrapper}
				contentContainerStyle={styles.contentContainer}
				data={players}
				renderRow={this.renderRow}
/>

The renderRow function and the callback functions. The data is correctly represented in the PointsItem on render. Same goes for the scores which are correctly fetched from the state:

     renderRow = ({data}) => {
	return <PointsItem  key={data.id} id={data.id} score={this.state.scores[data.id]} 
		onIncrement={this.incrementScore}
		onDecrement={this.decrementScore}/>
}

    incrementScore(playerID){
	var arrayVar = this.state.scores;
	arrayVar[playerID] = arrayVar[playerID] + 1;
	this.setState({ 
		scores: arrayVar 
	});
}
	
    decrementScore(playerID){
	var arrayVar = this.state.scores;
	if(arrayVar[playerID] > 0){
		arrayVar[playerID] = arrayVar[playerID] - 1;
		this.setState({ 
			scores: arrayVar 
		});
	}
}

the PointsItem component:

    class PointsItem extends React.Component{
	constructor(props){
		super(props);
	}
	render(){
		function playerWrapper(color){
			return {
				width: 50,
				height: 50,
				backgroundColor: color,
				flexDirection: 'row',
				marginLeft: 30,
				justifyContent: 'center',
				alignItems: 'center',
			}
		}
		
		function itemWrapper(){
			return {
				height: 70,
				width: window.width,
				flexDirection: 'row',
				alignItems: 'center',
				backgroundColor: '#fff',
				marginTop: 5,
				opacity: 1,
			}
		}
	
		return <Animated.View style={itemWrapper()}>
			<View style={playerWrapper(playerColors[this.props.id])}>
				<Text style={styles.points}>{this.props.id + 1}</Text>
			</View>
			<TouchableOpacity onPress={() => this.props.onDecrement(this.props.id)}>
				<View style={styles.decrementBox}>
					<Image source={img.toggleDown} />
				</View>
			</TouchableOpacity>
			<View style={styles.pointBox}>
				<Text style={styles.points}>{this.props.score}</Text>
			</View>
			<TouchableOpacity onPress={() => this.props.onIncrement(this.props.id)}>
				<View style={styles.incrementBox}>
					<Image source={img.toggleUp} />
				</View>
			</TouchableOpacity>
		</Animated.View>
	}
}

**Comment by gitim** [comment]
Looks like the problem caused by passing callbacks without binding this
```js
<PointsItem  key={data.id} id={data.id} score={this.state.scores[data.id]} 
	onIncrement={this.incrementScore}
	onDecrement={this.decrementScore}
```

try to bind
```js
<PointsItem  key={data.id} id={data.id} score={this.state.scores[data.id]} 
	onIncrement={this.incrementScore.bind(this)}
	onDecrement={this.decrementScore.bind(this)}
```
or you can wrap them with arrow functions
```js
<PointsItem  key={data.id} id={data.id} score={this.state.scores[data.id]} 
	onIncrement={(...args) => this.incrementScore(...args)}
	onDecrement={(...args) => this.decrementScore(...args)}
```

**Comment by DigohD** [comment]
Thanks!

**Comment by joehink** [comment]
I'm having the same problem except I have bound the function in the constructor.

resetList is undefined inside my Row component.

`constructor(props) {
        super(props);
        this.resetList = this.resetList.bind(this);
        this.props.navigation.addListener('willFocus', this.resetList)  
        this.state = { list: {} };
    }
    resetList() {
        AsyncStorage.getItem("list").then(list => {
            this.setState({ list: JSON.parse(list) })
        })
    }
    _renderRow({data, active}) {
        return (
            <Row data={data} active={active} resetList={this.resetList}/>
        )
    }
    renderList() {
        if (!!this.state.list) {
            return (
                <SortableList
                    style={styles.list}
                    contentContainerStyle={styles.contentContainer}
                    data={this.state.list}
                    renderRow={this._renderRow} 
                    manuallyActivateRows
                />
            )
        } else {
            return <Text>No Tasks</Text>
        }
    }`
