### ISSUE TITLE
SortableList sometimes does not render at all.

### ISSUE THREAD

**Issue by DigohD** [gitim/react-native-sortable-list#56]
Hello!

I have encountered a bizarre issue where the sortable list fails to render about 10% of the time. The parent component does render, and I know this since I have a test <Text> tag before the list which is rendered correctly. The data passed to the list is the same every time and does not change. The data is simply an array containing 6 numbers. Any ideas?

`<SortableList	style={layoutStyles.wrapper}
contentContainerStyle={layoutStyles.contentWrapper}
data={testData}
renderRow={this._renderRow} 
renderFooter={this._renderFooter} 
sortingEnabled={this.state.isSorting}/>`

**Comment by gitim** [comment]
HI! SortableList requires data to be object, try to pass object.

**Comment by KyleKhalaf** [comment]
I am having the same problem, and I could not find the pattern still. 

P.S data is an object.

**Comment by DigohD** [comment]
Thanks! Passing an object instead of an array makes no difference as far as I can tell though. About 10% of the time the list simply does not render. The random nature of the issue makes it near impossible to reproduce indeed. It's a shame, since the 90% of times it is working, it is excellent.

**Comment by luisfuertes** [comment]
I report it [here](https://github.com/gitim/react-native-sortable-list/issues/50)

I try to fix but cant find the error. I think is something with local variables.

The failing function is:
``` 
 _onUpdateLayouts() {
    Promise.all([this._footerLayout, ...this._rowsLayouts])
       .then(([footerLayout, ...rowsLayouts]) => {
           // <----- NEVER ENTER HERE
    });
}
```

**Comment by gitim** [comment]
could you try version from this branch https://github.com/gitim/react-native-sortable-list/tree/fix

**Comment by luisfuertes** [comment]
Cant compile, "nextOrder" is read-only

**Comment by luisfuertes** [comment]
SyntaxError /react-native-sortable-list/src/SortableList.js "nextOrder" is read-only

**Comment by gitim** [comment]
fixed

**Comment by DigohD** [comment]
I now get: "undefined is not an object (Evaluating this.props.order.forEach)" in componentWillMount()

**Comment by luisfuertes** [comment]
> I now get: "undefined is not an object (Evaluating this.props.order.forEach)" in componentWillMount()

Yes, same problem

**Comment by gitim** [comment]
> I now get: "undefined is not an object (Evaluating this.props.order.forEach)" in componentWillMount()

it is bug, we should iterate over state.order here.

**Comment by luisfuertes** [comment]
Updated to 
```
  componentWillMount() {

    this.props.order && this.props.order.forEach((key) => {
      this._rowsLayouts[key] = new Promise((resolve) => {
        this._resolveRowLayout[key] = resolve;
      });
    });
```

and now:
![captura de pantalla 2017-07-06 a las 12 11 57](https://user-images.githubusercontent.com/18212615/27906557-5544a630-6244-11e7-9f0f-efdd96b8f0ff.png)

**Comment by DigohD** [comment]
I should be this.state.order right?

`this.state.order.forEach((key) => {
      this._rowsLayouts[key] = new Promise((resolve) => {
        this._resolveRowLayout[key] = resolve;
      });
    });`

But then I get: (Undefined not an object: rowsLayouts[key].height) on line 219

**Comment by gitim** [comment]
> I should be this.state.order right?

yes

> But then I get: (Undefined not an object: rowsLayouts[key].height) on line 219

strange, Basic example seems works fine

**Comment by gitim** [comment]
try to log rowsLayouts in 218 line, it should contain layouts for row keys

**Comment by luisfuertes** [comment]
I fixed it wiht: 
``` 
  componentWillMount() {

    let order = this.getOrder()

    order.forEach((key) => {
      this._rowsLayouts[key] = new Promise((resolve) => {
        this._resolveRowLayout[key] = resolve;
      });
    });

    if (this.props.renderFooter && !this.props.horizontal) {
      this._footerLayout = new Promise((resolve) => {
        this._resolveFooterLayout = resolve;
      });
    }
  }

  getOrder() {
    let order = []
    if(this.props.order) {
      order = this.props.order
    } else {
      Object.keys(this.props.data).forEach((key, i) => {
        order.push(i.toString())
      })
    }
    return order
  }
```

**Comment by gitim** [comment]
@luisfuertes this commit https://github.com/gitim/react-native-sortable-list/commit/e99beff4b5575b23787db71738b8fb8afd0c4721  should fix it

**Comment by DigohD** [comment]
Logged rowsLayouts  and it prints an empty object {}

**Comment by luisfuertes** [comment]
Yes, @gitim your commit fix it too

**Comment by DigohD** [comment]
If I pass an array as the data it works.

```
// This data causes the error, but worked with master-branch version
const testData = {
	data1: 0,
	data2: 1,
	data3: 2,
	data4: 3,
	data5: 4,
	data6: 5,
};

// This data works
const testData2 = [0, 1, 2, 3, 4, 5];

```

**Comment by gitim** [comment]
> Logged rowsLayouts and it prints an empty object {}

it is strange how it crashes on 219 line, because for empty object, Object.keys(rowsLayouts) returns empty array and forEach will not iterate at all.

**Comment by DigohD** [comment]
I am new to React Native and Javascript in this kind of context so I might have messed something up. But weird indeed, the for loop should not iterate over an empty object. The array works fine though., so its probably something in the rest of my code that screws it up. Maybe my row items?

**Comment by gitim** [comment]
@DigohD I fixed it

**Comment by DigohD** [comment]
Confirmed working! 

Thanks for the help and for providing this great module!

**Comment by gitim** [comment]
Cool, will publish a new version very soon!

**Comment by gitim** [comment]
release 0.0.15

**Comment by luisfuertes** [comment]
Thanks! Good job.

My last suggestion is that apply scrollView style prop, for set padding.

If you add padding to container, rows dont render above container view. Need add to scrollView style.

Regards

**Comment by gitim** [comment]
@luisfuertes
> My last suggestion is that apply scrollView style prop, for set padding.

> If you add padding to container, rows dont render above container view. Need add to scrollView style.

`contentContainerStyle` prop is exactly what you need, isn't it?

**Comment by luisfuertes** [comment]
Oh yes i dindnt see, sorry

**Comment by KyleKhalaf** [comment]
Guys thanks for your good work. So how can I update my local version so that I get this fix?

**Comment by gitim** [comment]
just update to 0.0.15

**Comment by ArturGr** [comment]
still have this bug.

**Comment by afizboltz** [comment]
yup, still got this problem.
