### ISSUE TITLE
Change Height at Runtime

### ISSUE THREAD

**Issue by felangga** [gitim/react-native-sortable-list#57]
When I changing height at runtime, the card will overlapped. 
How can I re-render the list, so it will calculated new height ?

Picture here http://i67.tinypic.com/v7y4x4.png

**Comment by gitim** [comment]
SortableList does not expects that height of rows can change, it recalculates layouts if data or order change, it shallowly compares them when new props are received, so you need to change keys or values in data, so that shallow comparing will return false.
