### ISSUE TITLE
Not able to move an item top of the list and selection happens only after slight after scroll.

### ISSUE THREAD

**Issue by mamidala** [gitim/react-native-sortable-list#6]
Hi,
In iOS it is observed that an list item can be placed to bottom of the list, when we bring an item to bottom list scroll till the we get the bottom item then we can place the dragged item.
It is not happening if we want to move an item top of the list, once we drag the item to top  the list wont scroll so we wont be able to move the item to top of the list.
And the other issue is like item selection wont happen immediately, it takes slight time after the scroll has stopped.

Your sortable list looks awesome.Greatly appreciated.

Thanks,
Mahender

**Comment by gitim** [comment]
Hi, @mamidala! 
> It is not happening if we want to move an item top of the list, once we drag the item to top the list wont scroll so we wont be able to move the item to top of the list.

Maybe I don't understand you, but autoscroll is working in the example in both direction. 
<details>
<summary>gif</summary>
![-05-2016 12-26-24](https://cloud.githubusercontent.com/assets/3778452/20879824/831666c6-bae6-11e6-8c01-2387901349fb.gif)
</details>
Could you share your example?

> And the other issue is like item selection wont happen immediately, it takes slight time after the scroll has stopped.

yes, the scroll must stop before dragging, and there is small delay for long press (https://github.com/gitim/react-native-sortable-list/blob/master/src/Row.js#L5), but it doesn't look like an issue for ux.

**Comment by mamidala** [comment]
Please find my explanation below.
e.g  There are 15 items in the list. and currently items 10-16 visible in the list view.
       when i try to move the item no.13 top of the list am not able to move to top of the list above item       no.1.
Am able to to place above item no.10 but am not able to move the item to till item no.1 which is at top.
Hope this helps you to understand.
Thanks,
Mahender

**Comment by drewvolz** [comment]
I am witnessing this behavior as well on an iOS device... wonder what is going on with `AutoScroll`.

**Comment by gitim** [comment]
Now I see, thanks for your feedback! Fixed in 46d49644f3ab89a15f1ff3b183a1027364a39dd5
