### ISSUE TITLE
Expose toggleActive to children

### ISSUE THREAD

**Issue by bradbumbalough** [gitim/react-native-sortable-list#65]
Hello, I'm coming to this package from [react-native-sortable-listview](https://github.com/deanmcpherson/react-native-sortable-listview), because it was really buggy. This is a much cleaner implementation.

However, one thing that was nice about the other package was that it would pass the the toggleActive prop down in renderRow to the children, so that you could manually invoke the sorting. My use case is I have a lot of touches going on in my row and the PanResponder is "assuming" control over all of them. Ideally, I'd be able to trigger the activation of a row in my own Touchable component. 

I think we would just have to pass `_toggleActive` into the children. I can submit a PR for this assuming you're ok with the change. Do you see any issues or better means to implement?

Thank you!

**Comment by adriennetran** [comment]
@bradbumbalough I've been experiencing the same issue, and would really like to see this.

**Comment by bradbumbalough** [comment]
@adriennetran I just submitted a PR for this. You can try it out on my fork too... let me know if this would work for you. So far it has been working for my app. https://github.com/bradbumbalough/react-native-sortable-list/tree/bb/performance

**Comment by gitim** [comment]
Released a new version with cherry-picked commit, that adds this feature, closing this.
