### ISSUE TITLE
Breaks production builds in RN 0.49.1

### ISSUE THREAD

**Issue by joncursi** [gitim/react-native-sortable-list#68]
In RN 0.49.1 apps, when __DEV__ is false, this happens:

![screen shot 2017-10-05 at 12 54 26 pm](https://user-images.githubusercontent.com/4974609/31239806-57cb7dc8-a9cc-11e7-9529-de5befaf44ad.png)

Cause of the issue: https://github.com/gitim/react-native-sortable-list/blob/master/src/SortableList.js#L20-L21

**Comment by gitim** [comment]
released fix in 0.0.18
