### ISSUE TITLE
Autoscroll is a little too eager

### ISSUE THREAD

**Issue by drewvolz** [gitim/react-native-sortable-list#7]
It is a bit challenging to move around items around on the bottom half without them being automatically pushed upwards.

Steps to reproduce:
1. Scroll to bottom of list view
2. Select an item to move up or down (both directions cause the behavior)
3. Notice the view autoscroll upwards past the half-way mark of the list

**Comment by drewvolz** [comment]
I have a feeling that [line 123](https://github.com/gitim/react-native-sortable-list/commit/46d49644f3ab89a15f1ff3b183a1027364a39dd5#diff-e7d95e98bb0472979c2ad48071012cb9R123) may be responsible. Without adding `containerLayout.height`, I do not notice the functionality.

`keyY > this._contentOffset.y + containerLayout.height`

**Comment by gitim** [comment]
Do you mean we need some delay before autoscroll will activate? Currently it starts immediately when your touch reaches autoscroll area (60 px from top and 60 px from bottom).

**Comment by drewvolz** [comment]
I am not sure what is needed to change, exactly. When I select something to move around, it appears to be moved upwards without my "permission". It will be dragged upwards even if I am trying to move it downwards. 

This only seems to happen on the bottom of the list, from what I have noticed and tested. Maybe it is default functionality? But it appears different from v0.0.3 of react-native-sortable-list.

I would expect it not to automatically scroll the screen upwards either way, until I reach part of the screen where I need the view to autoscroll, such as the bottom of the screen when I am at the top of the list, or the top of the screen when I am at the bottom of the list.

**Comment by gitim** [comment]
I am trying investigate the problem, have not yet reproduced. @drewvolz is it can be reproduced in the example app? Or maybe you have code snippet for demonstrating?

**Comment by drewvolz** [comment]
I cannot reproduce this any longer.

**Comment by gitim** [comment]
Cool!
