### ISSUE TITLE
Upgraded to RN 0.50.3, no longer building with SortableList

### ISSUE THREAD

**Issue by Sammckay12** [gitim/react-native-sortable-list#72]
When building a Release version in the build configs including the SortableList now kills the thread. I know ListView is now deprecated and have had to swap out for FlatList where this occurs and maybe this could be related? Any thoughts on how to solve this or other ideas on what's causing this?

Thank you!

<img width="1131" alt="screen shot 2017-11-14 at 17 27 43" src="https://user-images.githubusercontent.com/21035838/32794623-4004e67a-c961-11e7-9ed7-089a529844ff.png">

**Comment by gitim** [comment]
Updated examples to 0.50.3, work w/o crashes, seems the issue not related to this module.
