### ISSUE TITLE
Drag handler which allow dragging item when long-touch on specific part of the list item

### ISSUE THREAD

**Issue by haotangio** [gitim/react-native-sortable-list#74]
I want to implement a sortable list where users are only be able to change the order by long-touch a specific part of the row (drag handler).

How can we do that with `react-native-sortable-list`?

**Comment by gitim** [comment]
There is a pr https://github.com/gitim/react-native-sortable-list/pull/66 that adds passing toggleRowActive function into rows, think I will cherry-pick this feature from the pr

**Comment by gitim** [comment]
Released 0.0.19 with toggleRowActive feature, see 8313356
