### ISSUE TITLE
Cells are not tappable if sortingEnabled has been set to false.

### ISSUE THREAD

**Issue by ccreonopoulos** [gitim/react-native-sortable-list#77]
Hi,

I have a SortableList that is filtered and I want to conditionally enable sorting for specific filters.
Unfortunately I have ran into an issue where passing the `sortingEnabled={false}` prop, stops the `onPressRow` from ever getting called on tap, disabling the cells from performing other actions when selected.

**Comment by sunilshenoy** [comment]
+1
