### ISSUE TITLE
Not Rendering The Data After Added A New Data Into Sortable List

### ISSUE THREAD

**Issue by chongzheng1995** [gitim/react-native-sortable-list#79]
Hello,

Good day and thanks for this awesome package. I am new to this React Native project. The followings are my datasource for the Sortable List.

`const data = {`
     ` 0 : {'id' : 'img1', 'imgsrc' : require('../img/food.png'), 'name':'Food'},`
     ` 1 : {'id' : 'img2', 'imgsrc' : require('../img/drink.png'), 'name':'Drink'},`
     ` 2 : {'id' : 'img3', 'imgsrc' : require('../img/building.png'), 'name':'Building'},`
     ` 3 : {'id' : 'img4', 'imgsrc' : require('../img/shop.png'), 'name':'Store'},`
     ` 4 : {'id' : 'img5', 'imgsrc' : require('../img/inventory.png'), 'name':'Inventory'},`
`}` 

Then, I created sortable list which successfully display all the items in the list as shown in below.
![Uploading ^9146803855146ED6D9EFA0676085AA998B2E266DFB496E8ADD^pimgpsh_mobile_save_distr.jpg…]()

However, when I added one item by the following function, the Sortable List does not render the new data.

`insertItem = (newId, newImgsrc, newName) => {`
`newItem = {'id': newId, 'imgsrc': newImgsrc, 'name': 'newName'};`
`length = Object.keys(this.state.data).length;`
`let tempdata = this.state.data;`
`tempdata[length] = newItem;`
`this.setState({data:tempdata});`
`}`

The Sortable List remained the same after adding new item. After inspection, I verified that there is additional data inside the this.state.data.

**Expected Output: Sortable List should render the new data**
**Actual Output: Sortable List does not render the new data**

**What Have I Tried:**
1. I have tried setState for the order variable to the whole list with additional data. Then, I encountered error of 'undefined is not an object (evaluating 'rowsLayout[key].height').

Thank you for your time and sorry for my lack of knowledge in React-Native.

**Comment by rammi44** [comment]
addNote(item) {
          if (item) {
            // this.state.todoItemArray.push({ 'Item': item, 'TodoItemstyle': todoItembgStyle });

            this.state.todoItemArray = this.state.todoItemArray.**concat**({ 'Item': item, 'TodoItemstyle': todoItembgStyle });

                     this.setState({
                todoItemArray: this.state.todoItemArray,
                         });
        }
        else {
            alert('Action Can not be empty');
        }
    }


Add this new item.. dont use push.. use concat...

**Comment by amed** [comment]
use es6 concatenating shortcut:

```
theHandler() {
    this.setState({
      stateName: [...this.state.stateName, newItem]
    })
  }
```
